### ISSUE TITLE
Support component options including providers

### ISSUE THREAD

**Issue by pkspks** [cnunciato/ng2-mock-component#19]
It is not possible to mock a component with providers. This is useful for a component that is a controlValueAccessor.

Fixed in #18

**Comment by bmtheo** [comment]
Hey, just +1ing here because our team also need that feature

Related SO question :
https://stackoverflow.com/questions/57168077/how-to-fix-error-no-value-accessor-for-form-control-with-name-in-angular-unit

**Comment by bmtheo** [comment]
Just realised the issue is more than 1 year old, @cnunciato should we consider this as "won't do" ?

@pkspks seems to have resolved the issue with https://github.com/cnunciato/ng-mock-component/pull/18, will you merge it ?

Thanks

**Comment by cnunciato** [comment]
Sorry for the delay! I simply lost sight of this.
