### ISSUE TITLE
The type of EventEmitter is better be any

### ISSUE THREAD

**Issue by penghuili** [cnunciato/ng2-mock-component#2]
Thank for this simple but helpful solution firstly.

The problem:

Let's say we have a very simple Component:
@Component({
    selector: "simple-one",
    template: "I like simple"
})
export class SimpleOneComponent {
    @Output() clicked = new EventEmitter\<string\>();
}

The problem is the type of the output, it's a string, but in the source code:
metadata.outputs.forEach((method) => {
    Mock.prototype[method] = new EventEmitter\<Object\>();
});

output type is always Object, which runs into errors.

Solution:
Change the output type to any. I have tried this, no more err~

**Comment by SampsonCrowley** [comment]
Pull request for this same reason made.

issue is resolved once merged
