### ISSUE TITLE
Error in typescript 2.4

### ISSUE THREAD

**Issue by jdeboer-geoplan** [cnunciato/ng2-mock-component#8]
I get this error with typescript 2.4

Type 'typeof Mock' has no properties in common with type 'Component'.

Known breaking issue with typescript https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes

**Comment by cnunciato** [comment]
Interesting, thanks for the head's up. I'll take a look -- planning to do another release of this shortly.

**Comment by aytacworld** [comment]
a workaround would be casting Mock to any
`return Component(metadata)(<any>Mock);`
But it's not a real solution.
Or you can downgrade your typescript package and make sure, your compiler and editor uses that one (https://stackoverflow.com/a/44858294)

**Comment by shaungrady** [comment]
👍

**Comment by cnunciato** [comment]
This should be fixed in 0.1.0; I went ahead with the casting approach, as it seemed reasonable enough.

**Comment by musasesay** [comment]
Type 'typeof HomePage' has no properties in common with type 'Component'.

**Comment by valueice** [comment]
Was anyone able to solve this? Had same error:
[TS] Type 'typeof HomePage' has no properties in common with type 'Component'.
